// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9Y9LcN7E1WOkRIqapxGCYE_KHuuooqQ',
    appId: '1:310051735931:web:c1b291a6252c9477a995de',
    messagingSenderId: '310051735931',
    projectId: 'ecommerce-320a1',
    authDomain: 'ecommerce-320a1.firebaseapp.com',
    storageBucket: 'ecommerce-320a1.firebasestorage.app',
    measurementId: 'G-6RPY3MDLVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcc0oI3adxMF5u3T7hM4-eB8UySGY3cE',
    appId: '1:310051735931:android:8c89bf156607dd7ea995de',
    messagingSenderId: '310051735931',
    projectId: 'ecommerce-320a1',
    storageBucket: 'ecommerce-320a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGuh-niuwZUY3v4E_bzr9WiuQOHshXSy0',
    appId: '1:310051735931:ios:e63c25ffcd80480ea995de',
    messagingSenderId: '310051735931',
    projectId: 'ecommerce-320a1',
    storageBucket: 'ecommerce-320a1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGuh-niuwZUY3v4E_bzr9WiuQOHshXSy0',
    appId: '1:310051735931:ios:e63c25ffcd80480ea995de',
    messagingSenderId: '310051735931',
    projectId: 'ecommerce-320a1',
    storageBucket: 'ecommerce-320a1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL9Y9LcN7E1WOkRIqapxGCYE_KHuuooqQ',
    appId: '1:310051735931:web:f10001b3048d295ea995de',
    messagingSenderId: '310051735931',
    projectId: 'ecommerce-320a1',
    authDomain: 'ecommerce-320a1.firebaseapp.com',
    storageBucket: 'ecommerce-320a1.firebasestorage.app',
    measurementId: 'G-J3B8FPXJ11',
  );
}
